name: device_apps
description: Plugin to get the list of applications installed on the device (Android only)
version: 1.0.9
homepage: https://github.com/g123k/flutter_plugin_device_apps

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.g123k.deviceapps
        pluginClass: DeviceAppsPlugin

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"